version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__WEAVIATE_URL=http://weaviate:8080
      - RAG_SHARED__WEAVIATE_INDEX=rag_documents
      - RAG_SHARED__EMBEDDING_SERVICE_URL=http://embed:9000
      - RAG_SHARED__REDIS_URL=redis://redis:6379/0
      - RAG_SHARED__POSTGRES_DSN=postgresql+asyncpg://rag:rag@postgres:5432/rag
      - RAG_SHARED__ALLOWED_CORS_ORIGINS=http://localhost:3000
      - RAG_SHARED__ENABLE_PERMISSION_FILTERS=${RAG_SHARED__ENABLE_PERMISSION_FILTERS:-true}
      - RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL=${RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL:-public}
      - RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS=${RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS:-900}
      - RAG_SHARED__SHAREPOINT_TENANT_ID=${RAG_SHARED__SHAREPOINT_TENANT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_ID=${RAG_SHARED__SHAREPOINT_CLIENT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_SECRET=${RAG_SHARED__SHAREPOINT_CLIENT_SECRET}
      - RAG_SHARED__SHAREPOINT_SITE_IDS=${RAG_SHARED__SHAREPOINT_SITE_IDS}
    ports:
      - "8000:8000"
    depends_on:
      - embed
      - weaviate
      - redis
      - postgres
    networks:
      - rag-net

  worker:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__WEAVIATE_URL=http://weaviate:8080
      - RAG_SHARED__WEAVIATE_INDEX=rag_documents
      - RAG_SHARED__EMBEDDING_SERVICE_URL=http://embed:9000
      - RAG_SHARED__REDIS_URL=redis://redis:6379/0
      - RAG_SHARED__OBJECT_STORE_ENDPOINT=http://minio:9000
      - RAG_SHARED__OBJECT_STORE_ACCESS_KEY=minioadmin
      - RAG_SHARED__OBJECT_STORE_SECRET_KEY=minioadmin
      - RAG_SHARED__ENABLE_PERMISSION_FILTERS=${RAG_SHARED__ENABLE_PERMISSION_FILTERS:-true}
      - RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL=${RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL:-public}
      - RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS=${RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS:-900}
      - RAG_SHARED__SHAREPOINT_TENANT_ID=${RAG_SHARED__SHAREPOINT_TENANT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_ID=${RAG_SHARED__SHAREPOINT_CLIENT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_SECRET=${RAG_SHARED__SHAREPOINT_CLIENT_SECRET}
      - RAG_SHARED__SHAREPOINT_SITE_IDS=${RAG_SHARED__SHAREPOINT_SITE_IDS}
    depends_on:
      - redis
      - embed
      - weaviate
    networks:
      - rag-net
    volumes:
      - ./data:/data

  scheduler:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    command: celery -A worker beat --loglevel=info
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__WEAVIATE_URL=http://weaviate:8080
      - RAG_SHARED__WEAVIATE_INDEX=rag_documents
      - RAG_SHARED__EMBEDDING_SERVICE_URL=http://embed:9000
      - RAG_SHARED__REDIS_URL=redis://redis:6379/0
      - RAG_SHARED__OBJECT_STORE_ENDPOINT=http://minio:9000
      - RAG_SHARED__OBJECT_STORE_ACCESS_KEY=minioadmin
      - RAG_SHARED__OBJECT_STORE_SECRET_KEY=minioadmin
      - RAG_SHARED__ENABLE_PERMISSION_FILTERS=${RAG_SHARED__ENABLE_PERMISSION_FILTERS:-true}
      - RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL=${RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL:-public}
      - RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS=${RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS:-900}
      - RAG_SHARED__SHAREPOINT_TENANT_ID=${RAG_SHARED__SHAREPOINT_TENANT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_ID=${RAG_SHARED__SHAREPOINT_CLIENT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_SECRET=${RAG_SHARED__SHAREPOINT_CLIENT_SECRET}
      - RAG_SHARED__SHAREPOINT_SITE_IDS=${RAG_SHARED__SHAREPOINT_SITE_IDS}
    depends_on:
      - redis
    networks:
      - rag-net
    volumes:
      - ./data:/data

  file_watcher:
    build:
      context: .
      dockerfile: services/worker/Dockerfile
    command: python -m worker.watchers
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__WEAVIATE_URL=http://weaviate:8080
      - RAG_SHARED__WEAVIATE_INDEX=rag_documents
      - RAG_SHARED__EMBEDDING_SERVICE_URL=http://embed:9000
      - RAG_SHARED__REDIS_URL=redis://redis:6379/0
      - RAG_SHARED__ENABLE_PERMISSION_FILTERS=${RAG_SHARED__ENABLE_PERMISSION_FILTERS:-true}
      - RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL=${RAG_SHARED__DEFAULT_PUBLIC_PRINCIPAL:-public}
      - RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS=${RAG_SHARED__PRINCIPAL_CACHE_TTL_SECONDS:-900}
      - RAG_SHARED__SHAREPOINT_TENANT_ID=${RAG_SHARED__SHAREPOINT_TENANT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_ID=${RAG_SHARED__SHAREPOINT_CLIENT_ID}
      - RAG_SHARED__SHAREPOINT_CLIENT_SECRET=${RAG_SHARED__SHAREPOINT_CLIENT_SECRET}
      - RAG_SHARED__SHAREPOINT_SITE_IDS=${RAG_SHARED__SHAREPOINT_SITE_IDS}
    depends_on:
      - worker
    networks:
      - rag-net
    volumes:
      - ./data:/data

  embed:
    build:
      context: .
      dockerfile: services/embed/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RAG_SHARED__OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "9000:9000"
    networks:
      - rag-net

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - rag-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - rag-net

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=rag
      - POSTGRES_PASSWORD=rag
      - POSTGRES_DB=rag
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rag-net

  weaviate:
    image: semitechnologies/weaviate:1.24.6
    restart: unless-stopped
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: none
      QUERY_DEFAULTS_LIMIT: 20
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8080:8080"
    volumes:
      - weaviate-data:/var/lib/weaviate
    networks:
      - rag-net

  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - rag-net

volumes:
  postgres-data:
  weaviate-data:
  minio-data:

networks:
  rag-net:
    driver: bridge
